In [1]:
import numpy as np

def matrix_multiplication(A, B):
    """
    Perform matrix multiplication between two NumPy arrays.
    """
    if A.shape[1] != B.shape[0]:
        raise ValueError("Number of columns of A must match number of rows of B")
    return np.dot(A, B) 

# Matrix A
rows_A = int(input("Enter number of rows for Matrix A: "))
cols_A = int(input("Enter number of columns for Matrix A: "))

print("Enter elements of Matrix A row-wise (space-separated):")
A_elements = list(map(int, input().split()))
A = np.array(A_elements).reshape(rows_A, cols_A)

# Matrix B
rows_B = int(input("Enter number of rows for Matrix B: "))
cols_B = int(input("Enter number of columns for Matrix B: "))

print("Enter elements of Matrix B row-wise (space-separated):")
B_elements = list(map(int, input().split()))
B = np.array(B_elements).reshape(rows_B, cols_B)

#multiplication
try:
    result = matrix_multiplication(A, B)
    print("\nMatrix A:\n", A)
    print("\nMatrix B:\n", B)
    print("\nA x B:\n", result)
except ValueError as e:
    print("\nError:", e)


Enter number of rows for Matrix A:  2
Enter number of columns for Matrix A:  3


Enter elements of Matrix A row-wise (space-separated):


 1 2 3 4 5 6
Enter number of rows for Matrix B:  3
Enter number of columns for Matrix B:  2


Enter elements of Matrix B row-wise (space-separated):


 3 2 6 7 8 9



Matrix A:
 [[1 2 3]
 [4 5 6]]

Matrix B:
 [[3 2]
 [6 7]
 [8 9]]

A x B:
 [[39 43]
 [90 97]]


In [8]:
import numpy as np

# Example dataset 
data = np.array([10, 50, 60, 80, 100], dtype=float)
print("Original Data:", data)


Original Data: [ 10.  50.  60.  80. 100.]


In [9]:
# Min-Max Scaling
min_val = np.min(data)
max_val = np.max(data)
data_minmax_scaled = (data - min_val) / (max_val - min_val)

print("\nMin-Max Scaled Data:", data_minmax_scaled)


Min-Max Scaled Data: [0.         0.44444444 0.55555556 0.77777778 1.        ]


In [10]:
# Standardization 
mean_val = np.mean(data)
std_val = np.std(data)
data_standardized = (data - mean_val) / std_val

print("\nStandardized Data:", data_standardized)



Standardized Data: [-1.64845118 -0.32969024  0.          0.65938047  1.31876095]
